### ISSUE TITLE
Mensagens de erro significativas devem ser mostradas aos usuários

### ISSUE THREAD

**Issue by olimppb** [olimpiada-paraibana-de-informatica/frontend#8]
**Requisitos**
Quando um erro ocorre os usuários precisam saber o que exatamente ocorreu para tomar decisões sobre corrigí-lo. 

**Tasks**
- [ ] avaliar código do erro informado pelo back, se código de erro existe, então há uma mensagem amigável do back que deve ser mostrada ao usuário

_Sugiro fazer essa verificação via interceptador para qualquer requisição. Basta verificar se o status da resposta está no intervalo [400, 599]. Se estiver, indica erro. Se houver erro com errorCode na resposta significa que o backend tem uma mensagem amigável a ser mostrada, então basta mostrar no popup._

**Comment by erijonhson** [comment]
![image](https://user-images.githubusercontent.com/10831613/58223868-ca081280-7cf1-11e9-9809-b5aca9b93b7b.png)

O _errorCode_ existe, mas o front não verifica e mostra a mensagem adequadamente.

Sugiro fazer essa **verificação via interceptador para qualquer requisição**. Basta verificar se o status da solicitação está no intervalo [400, 599]. Se estiver, indica erro. Se houver erro com _errorCode_ na resposta significa que o backend tem uma mensagem amigável a ser mostrada, então basta mostrar no popup.
